---
title: "R Notebook"
---




```{r}
library(tidyverse)
library(glue)
library(SingleCellExperiment)
library(lemur)
source("util.R")
```





```{r}
fit_small <- qs::qread("../benchmark/output/glioblastoma/fit_hvg10k-small.qs") 
fit_small <- fit_small[,fit_small$colData$condition != "etoposide" & fit_small$colData$patient_id != "PW029"]
# Flip x axis for prettier figures
reducedDim(fit_small, "fit_al_umap")[,1] <- -reducedDim(fit_small, "fit_al_umap")[,1]
reducedDim(fit_small, "fit_umap")[,1] <- -reducedDim(fit_small, "fit_umap")[,1]
reducedDim(fit_small, "UMAP")[,2] <- -reducedDim(fit_small, "UMAP")[,2]

nei_pan_small <- qs::qread("../benchmark/output/glioblastoma/fit_hvg10k-nei_pan-small.qs")
nei_pan_mod <- qs::qread("../benchmark/output/glioblastoma/fit_hvg10-nei_pan-without_neighborhood.qs")
nei_pan_tumor_small <- qs::qread("../benchmark/output/glioblastoma/fit_hvg10k-nei_pan_tumor-small.qs")
psce_lmo2 <- qs::qread("../benchmark/output/glioblastoma/fit_hvg10k-lmo2_psce.qs")
full_row_data <- qs::qread("../benchmark/output/glioblastoma/fit_hvg10-rowdata.qs")
```

```{r}
# cell_type_colors <- structure(ggsci::pal_npg()(4), names = c("Tumor", "T cell", "Oligodendrocytes", "Myeloid"))
cell_type_colors <- structure(c("#FAC1BD", "#8dd3c7", "#80b1d3", "#b3de69"), names = c("Tumor cells", "T cells", "Oligodendrocytes", "Myeloid cells"))
ggplot(enframe(cell_type_colors), aes(x = name, y = 1)) +
    geom_tile(aes(fill = value)) +
    scale_fill_identity()
```


```{r}
# RColorBrewer::display.brewer.all()

# condition_colors<- structure(RColorBrewer::brewer.pal(n = 3, name = "Set2"), names = c("ctrl", "panobinostat", "etoposide"))
condition_colors <- structure(c("#fc8d62", "#8da0cb"), names = c("ctrl", "panobinostat"))

ggplot(enframe(condition_colors), aes(x = name, y = 1)) +
    geom_tile(aes(fill = value)) +
    scale_fill_identity()
```




```{r, paged.print=FALSE}
sel_genes <- c("CD14", "TYROBP", "PLP1", "MAG", "TRBC1", "TRBC2", "GAP43") 
ct_marker_genes <- tibble(gene = sel_genes, cell_type_marker = rep(c("Myeloid cells", "Oligodendrocytes", "T cells", "Tumor cells"), times = c(2,2,2,1)))

stopifnot(all(sel_genes %in% rowData(fit_small)$gene))
gene_ids <- deframe(as_tibble(rowData(fit_small)[c("gene", "gid")]))[sel_genes]
expr_mat <- counts(fit_small)[gene_ids, ]
cell_type_dot_plot <- as_tibble(as.matrix(t(expr_mat))) %>%
  mutate(cell_type = fit_small$colData$cell_type) %>%
  pivot_longer(-cell_type, names_to = "gene_id", values_to = "expr") %>%
  left_join(enframe(gene_ids,  name = "gene_name",value = "gene_id"), by = "gene_id") %>%
  summarize(mean_expr = mean(expr, trim = 0),
            frac_expr = mean(expr != 0),
            .by = c(cell_type, gene_id, gene_name)) %>%
  mutate(gene_name = fct_rev(factor(gene_name, levels = sel_genes))) %>%
  mutate(cell_type_short = case_when(
    cell_type == "Myeloid cells" ~  "Myel.",
    cell_type == "Oligodendrocytes" ~  "Oligo.",
    cell_type == "Tumor cells" ~  "Tumor",
    TRUE ~ cell_type
  )) %>%
  left_join(ct_marker_genes, by = c("gene_name" = "gene")) %>%
  ggplot() +
    geom_point(aes(x = cell_type_short, y = gene_name, color = log2(mean_expr + 1), size = frac_expr), stroke = 0) +
    geom_rect(data = ct_marker_genes, aes(xmin = 0.6, xmax = 0.75, ymin = -Inf, ymax=Inf, fill = cell_type_marker), show.legend=FALSE) +
    facet_grid(rows = vars(cell_type_marker), scales = "free_y") +
    colorspace::scale_color_continuous_sequential(limits = c(0, NA), breaks = c(0, 2, 4)) +
    scale_fill_manual(values = cell_type_colors) +
    scale_size_binned(range = c(0.01, 3), breaks = c(0, 0.25, 0.75, 1), limits = c(0, 1), labels = c(0, "", "", 1)) +
    scale_x_discrete(expand = expansion(add = 0.3)) +
    scale_y_discrete(expand = expansion(add = 0.4), labels = \(x) paste0("\\emph{", x, "}")) +
    coord_cartesian(clip = "off") +
    guides(color = guide_colorbar(barheight = unit(1, "mm"), barwidth = unit(5, "mm"), title.vjust = 0.25, label.position = "top", label.vjust = -2),
           size = guide_bins(label.vjust = -11)) +
    theme(axis.title = element_blank(), legend.position = c(0,-0.2), legend.direction = "horizontal",
          legend.box = "horizontal", legend.text = element_text(size = font_size_tiny),
          strip.background = element_blank(), strip.text = element_blank(), panel.spacing.y = unit(1.5, "mm")) +
    labs(size = "$\\text{frac}[y \\neq 0]$", color = "expression")

cell_type_dot_plot
```


```{r, paged.print=FALSE}
chr_ratio_pl <- colData(fit_small) %>%
  as_tibble() %>%
  dplyr::select(cell_type, chr_10_ratio, chr_7_ratio) %>%
  pivot_longer(starts_with("chr_"), names_to = "origin", values_to = "ratio") %>%
  mutate(is_tumor = cell_type == "Tumor cells") %>%
  ggplot(aes(x = ratio)) +
    geom_histogram(aes(fill = is_tumor), position = "identity", alpha = 0.7, show.legend = FALSE, bins = 500) +
    facet_wrap(vars(origin), nrow = 1, labeller = as_labeller(c(chr_10_ratio = "Chr.~10 Ratio", chr_7_ratio = "Chr.~7 Ratio")), scales = "free_y") +
    scale_y_continuous(expand = expansion(0)) +
    scale_x_continuous(expand = expansion(0), breaks = c(0, 1, 2)) +
    scale_fill_manual(values = c("TRUE" = unname(cell_type_colors["Tumor cells"]), "FALSE" = "#888888")) +
    coord_cartesian(xlim = c(0, 2.1)) +
    labs(x = "Expression ratio vs chr. 1-5", y = "No. cells") +
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

chr_ratio_pl
```

```{r}
# new_sel_genes <- c("HIST3H2A", "LMO2", "EPC1", "PTPRZ1", "HBEGF", "SPATA13", "MBP")
# gene2id <- deframe(full_row_data[,c("gene", "gid")])
# ctrl_proj <- lemur:::grassmann_map(lemur:::sum_tangent_vectors(fit_small$coefficients, c(1, 0, 0, rep(0, times = 5))), fit_small$base_point)[,1:2]
# pan_proj <- lemur:::grassmann_map(lemur:::sum_tangent_vectors(fit_small$coefficients, c(1, 0, 1, rep(0, times = 5))), fit_small$base_point)[,1:2]
# 
# rownames(ctrl_proj) <- full_row_data$gid
# rownames(pan_proj) <- full_row_data$gid
# 
# sqrt(rowSums2(ctrl_proj[gene2id[new_sel_genes],]^2))
# sqrt(rowSums2(pan_proj[gene2id[new_sel_genes],]^2))
```



```{r, paged.print=FALSE}
sel_genes <- c("CD14", "PLP1", "GAP43", "HIST3H2A", "EPC1")
is_marker_gene <- c("CD14" = TRUE, "PLP1" = TRUE, "GAP43" = TRUE, "HIST3H2A" = FALSE)

top_dirs <- deframe(full_row_data[,c("gene", "gid")])[sel_genes]

ctrl_proj <- lemur:::grassmann_map(lemur:::sum_tangent_vectors(fit_small$coefficients, c(1, 0, 0, rep(0, times = 5))), fit_small$base_point)[,1:2]
rownames(ctrl_proj) <- full_row_data$gid
ctrl_proj_df <- as_tibble(ctrl_proj[top_dirs,], rownames = "gid") %>%
  left_join(as_tibble(full_row_data))

pan_proj <- lemur:::grassmann_map(lemur:::sum_tangent_vectors(fit_small$coefficients, c(1, 0, 1, rep(0, times = 5))), fit_small$base_point)[,1:2]
rownames(pan_proj) <- full_row_data$gid
pan_proj_df <- as_tibble(pan_proj[top_dirs,], rownames = "gid") %>%
  left_join(as_tibble(full_row_data))

proj_df <- bind_rows(mutate(ctrl_proj_df, condition = "ctrl"),
                     mutate(pan_proj_df, condition = "panobinostat"))

manual_text_pos <- tribble(
       ~gene,   ~V1,  ~V2, ~hjust, ~vjust,
      "CD14",    15,   -4,     0,       0,
      "PLP1",     1,   18,   0.5,       0,
     "GAP43",   -15,   -9,     1,       0,
  "HIST3H2A",     4,  -18,     0,       0,
) %>%
  mutate(gene_label = paste0("\\emph{", gene, "}"))

# eto_proj <- lemur:::grassmann_map(lemur:::sum_tangent_vectors(fit_small$coefficients, c(1, 1, 0, rep(0, times = 5))), fit_small$base_point)[,1:2]
# rownames(eto_proj) <- full_row_data$gid
# eto_proj_df <- as_tibble(eto_proj[top_dirs,] * c(rep(200, 3), 2000), rownames = "gid") %>%
#   left_join(as_tibble(full_row_data))

z_base_space <- as_tibble(colData(fit_small)) %>%
  mutate(emb = t(fit_small$embedding[1:2,])) %>%
  ggplot(aes(x = emb[,1], y = emb[,2])) +
    ggrastr::rasterize(geom_point(aes(color = cell_type), size = 0.07, stroke = 0, show.legend = FALSE), dpi = 600) +
    scale_color_manual(values = cell_type_colors) +
    small_axis(label = "$\\matr{Z}$ space", xlim = c(-18, 40), ylim = c(-20, 25)) +
    labs(subtitle = "LEMUR's latent space ($\\matr{Z}$)\ncolored by cell type")


mc_biplot_marker <- as_tibble(colData(fit_small)) %>%
  mutate(emb = t(fit_small$embedding[1:2,])) %>%
  ggplot(aes(x = emb[,1], y = emb[,2])) +
    ggrastr::rasterize(geom_point(aes(color = cell_type), size = 0.07, stroke = 0, show.legend = FALSE), dpi = 600) +
    scale_color_manual(values = cell_type_colors) +
    ggnewscale::new_scale_colour() +
    geom_segment(data = proj_df %>% filter(is_marker_gene[gene]), aes(x = 0, y = 0, xend = V1 * 200, yend = V2 * 200, color = condition), linewidth = 1.2, show.legend = FALSE) +
    geom_point(data = proj_df %>% filter(is_marker_gene[gene]) %>% arrange(desc(condition)), aes(x = V1 * 200, y = V2 * 200, color = condition), size = 0.6, show.legend = FALSE) +
    scale_color_manual(values = condition_colors) +
    geom_text(data = manual_text_pos %>% filter(is_marker_gene[gene]), aes(x = V1, y = V2, hjust = hjust, vjust = vjust, label = gene_label), size = font_size_small / .pt) +
    # coord_fixed(ylim = c(-20, 25), xlim = c(-40, 20), clip = "off") +
    small_axis(label = "$\\matr{Z}$ space", xlim = c(-18, 40), ylim = c(-20, 25)) +
    labs(subtitle = "Marker genes projected on $\\matr{Z}$")
    
mc_biplot_diff <- as_tibble(colData(fit_small)) %>%
  mutate(emb = t(fit_small$embedding[1:2,])) %>%
  ggplot(aes(x = emb[,1], y = emb[,2])) +
    ggrastr::rasterize(geom_point(aes(color = cell_type), size = 0.07, stroke = 0, show.legend = FALSE), dpi = 600) +
    scale_color_manual(values = cell_type_colors) +
    ggnewscale::new_scale_colour() +
    geom_segment(data = proj_df %>% filter(!is_marker_gene[gene]) %>% arrange(desc(condition)), aes(x = 0, y = 0, xend = V1 * 2000, yend = V2 * 2000, color = condition),
                 linewidth = 1.2, show.legend = FALSE) +
    geom_point(data = proj_df %>% filter(!is_marker_gene[gene]) %>% arrange(desc(condition)), aes(x = V1 * 2000, y = V2 * 2000,color = condition), size = 0.6, show.legend = FALSE) +
    scale_color_manual(values = condition_colors) +
    geom_text(data = manual_text_pos %>% filter(!is_marker_gene[gene]), aes(x = V1, y = V2, hjust = hjust, vjust = vjust, label = gene_label), size = font_size_small / .pt) +
    # coord_fixed(ylim = c(-20, 25), xlim = c(-40, 20), clip = "off") +
    small_axis(label = "$\\matr{Z}$ space", xlim = c(-18, 40), ylim = c(-25, 20)) +
    labs(subtitle = "Gene with large expression change projected on $\\matr{Z}$")

mc_biplot_marker
mc_biplot_diff
```

```{r}
cell_type_legend_suppl <- ggplot(enframe(cell_type_colors), aes(x = 0, y = 0, color = name)) + 
  geom_point() + 
  scale_color_manual(values = cell_type_colors, name = "Cell types") +
  theme(legend.position = "bottom", legend.title = element_text(size = font_size_small))

annotation_pl <- cowplot::ggdraw() +
  cowplot::draw_label(x = 0.8, y = 0.1, label = "Three other cell types", size = font_size_small, hjust = 0) +
  cowplot::draw_line(x = c(0.9,  0.71), y = c(0.15, 0.5), size = 0.25) +
  cowplot::draw_label(x = 1, y = 0.6, label = "Tumor cells", size = font_size_small, hjust = 0, vjust = 0.5) +
  cowplot::draw_line(x = c(1, 0.82), y = c(0.6, 0.55), size = 0.2) 
```


```{r, paged.print=FALSE}
plot_assemble(add_text("(A) Glioblastoma cell type assignment", x = 1.5, y = 1.5, vjust = 1, fontsize = font_size, fontface = "bold"),
              add_plot(cowplot::get_legend(cell_type_legend_suppl), x = 3, y = 5, height = 5),
              add_plot(cell_type_dot_plot , x = 0, y = 10, width = 70, height = 40),
              
              add_text("(B) Aneuploidie", x = 95, y = 1.5, vjust = 1, fontsize = font_size, fontface = "bold"),
              add_plot(chr_ratio_pl, x = 95, y = 7, width = 60, height = 28),
              add_plot(annotation_pl, x = 95, y = 7, width = 60, height = 32),
              
              add_text("(C) Multi-condition biplots", x = 1.5, y = 62, vjust = 1, fontsize = font_size, fontface = "bold"),
              add_plot(z_base_space,  x = 0, y = 65, width = 55, height = 40),
              add_plot(mc_biplot_marker, x = 55, y = 65, width = 55, height = 40),
              add_plot(mc_biplot_diff, x = 110, y = 65, width = 55, height = 40),
              
              width = 170, height = 110, units = "mm", show_grid_lines = FALSE, latex_support = TRUE,
              filename = "../plots/suppl_glioblastoma_celltype_annotation.pdf")
```





Make UMAPs

```{r}
make_dim_pl <- function(red_dim, color_by = NULL, axis_label = ""){
  as_tibble(colData(fit_small)) %>%
    mutate(umap = reducedDim(fit_small, red_dim)) %>%
    sample_frac(n = 1) %>%
    ggplot(aes(x = umap[,1], y = umap[,2])) +
      ggrastr::rasterize(geom_point(aes(color = {{color_by}}), size = 0.02, stroke = 0, show.legend = FALSE), dpi = 600) +
      small_axis(label = axis_label, arrow_length = if(axis_label != "") 10 else 5)
}



umap_orig_ct_pl <- make_dim_pl("UMAP", color_by = cell_type, axis_label = "") +
  scale_color_manual(values = cell_type_colors)
umap_orig_pc_pl <- make_dim_pl("UMAP", color_by = condition, axis_label = "UMAP") +
  ggrepel::geom_text_repel(data = . %>% filter(cell_type == "Tumor cells") %>% summarize(umap = matrix(colMedians(umap), nrow = 1), .by = patient_id),
            aes(label = patient_id), size = font_size_tiny / .pt) +
  scale_color_manual(values = condition_colors)

umap_fit_ct_pl <- make_dim_pl("fit_umap", color_by = cell_type, axis_label = "") +
  scale_color_manual(values = cell_type_colors)
umap_fit_pc_pl <- make_dim_pl("fit_umap", color_by = condition, axis_label = "") +
  scale_color_manual(values = condition_colors)

umap_fital_ct_pl <- make_dim_pl("fit_al_umap", color_by = cell_type, axis_label = "") +
  scale_color_manual(values = cell_type_colors)
umap_fital_pc_pl <-make_dim_pl("fit_al_umap", color_by = condition, axis_label = "") +
  scale_color_manual(values = condition_colors)

umap_orig_ct_pl
umap_orig_pc_pl
```



```{r, paged.print=FALSE}
scale_sym <- function(x, ignore_extreme = 0){
  abs_max <- max(abs(quantile(x, c(ignore_extreme, 1-ignore_extreme))))
  x / abs_max
}

umap_fit <- reducedDim(fit_small, "fit_al_umap")
pan_genes_order <- c("HIST3H2A", "EPC1", "PTPRZ1", "HBEGF", "SPATA13", "MBP")

is_inside <- tibble(gid = rowData(fit_small)$gid, gene = rowData(fit_small)$gene, cell_id = list(colnames(fit_small))) %>%
  filter(gene %in% pan_genes_order) %>%
  left_join(dplyr::select(nei_pan_small, name, neighborhood), by = c("gid"= "name")) %>%
  mutate(inside = map2(cell_id, neighborhood, \(ref, nei_cells)ref  %in% nei_cells)) %>%
  dplyr::select(-neighborhood) %>%
  unnest(c(inside, cell_id)) %>%
  mutate(gene = factor(gene, levels = c(pan_genes_order[1], "LMO2", pan_genes_order[-1]))) 

is_inside <- bind_rows(is_inside, tibble(gid = rowData(fit_small)$gid, gene = rowData(fit_small)$gene, cell_id = list(colnames(fit_small))) %>%
  filter(gene %in% "LMO2") %>%
  left_join(dplyr::select(nei_pan_tumor_small, name, neighborhood), by = c("gid"= "name")) %>%
  mutate(inside = map2(cell_id, neighborhood, \(ref, nei_cells)ref  %in% nei_cells)) %>%
  dplyr::select(-neighborhood) %>%
  unnest(c(inside, cell_id)) %>%
  mutate(gene = factor(gene, levels = c(pan_genes_order[1], "LMO2", pan_genes_order[-1]))))

de_regions_maps <- nei_pan_small %>%
  unnest(neighborhood) %>%
  left_join(tibble(umap = umap_fit, neighborhood = rownames(umap_fit)), by = "neighborhood") %>%
  left_join(as_tibble(full_row_data), by = c("name" = "gid")) %>%
  filter(gene %in% pan_genes_order) %>%
  mutate(gene = factor(gene, levels = pan_genes_order)) 
  

de_regions_maps2 <- nei_pan_tumor_small %>%
  unnest(neighborhood) %>%
  left_join(tibble(umap = umap_fit, neighborhood = rownames(umap_fit)), by = "neighborhood") %>%
  left_join(as_tibble(full_row_data), by = c("name" = "gid"))


de_plot_data <- as_tibble(colData(fit_small), rownames = "cell_id") %>%
  mutate(umap = umap_fit) %>%
  mutate(de = as_tibble(t(assay(fit_small, "DE_panobinostat")))) %>%
  unnest(de, names_sep = "-") %>%
  pivot_longer(starts_with("de-"), names_sep = "-", values_to = "de", names_to = c(NA, "gid")) %>%
  inner_join(as_tibble(full_row_data), by = "gid") %>%
  filter(gene %in%  c(pan_genes_order, "LMO2")) %>%
  mutate(gene = factor(gene, levels = c(pan_genes_order[1], "LMO2", pan_genes_order[-1]))) %>%
  left_join(is_inside, by = c("gid", "gene", "cell_id")) %>%
  mutate(inside = ifelse(inside, "in", "out")) %>%
  mutate(inside = factor(inside, levels = c("in", "out")))  %>%
  sample_frac(size = 1) 

de_plots <- de_plot_data %>%
  filter(gene != "LMO2" | cell_type == "Tumor cells") %>%
  group_by(gene) %>%
  group_map(\(data, key){
    abs_max <- max(abs(quantile(data$de, c(0.95, 0.05))))
    data$gene <- key[[1]][1]
    ggplot(data, aes(x = umap[,1], y = umap[,2])) +
      ggrastr::rasterise(geom_point(aes(color = de), size = 0.05, stroke = 0), dpi = 600) +
      # scale_colour_gradient2_rev(limits = c(-1, 1) * abs_max, oob = scales::squish, breaks = c(-1, 0, 1) * signif_to_zero(abs_max, 1), mid = "lightgrey") +
      scale_color_de_gradient(abs_max, mid_width = 0.2) +
      facet_grid(vars(inside), vars(gene), labeller = labeller(inside =as_labeller( c("in" = "Cells in Neighb.", "out" = "All other cells")),
                                                               gene = as_labeller(\(x) paste0("\\emph{", x, "}"))), switch = "y")  +
      scale_x_continuous(limits = range(umap_fit[,1]) * 1.1) +
      scale_y_continuous(limits = range(umap_fit[,2]) * 1.1) +
      small_axis(label = "", fontsize = font_size_tiny, xlim = range(umap_fit[,1]), ylim = range(umap_fit[,2]), arrow_length = 3) +
      guides(color = guide_colorbar(barheight = unit(1, "mm"), title = "")) +
      theme(panel.spacing.x = unit(5, "mm"), legend.position =  "bottom") 
  }) %>%
  cowplot::plot_grid(plotlist = ., nrow = 1)

de_plots

de_plot_data_hist3h2a <- de_plot_data %>%
  filter(gene == "HIST3H2A")
abs_max <- max(abs(quantile(de_plot_data_hist3h2a$de, c(0.95, 0.05))))

de_plot_full <- ggplot(de_plot_data_hist3h2a, aes(x = umap[,1], y = umap[,2])) +
    ggrastr::rasterise(geom_point(aes(color = de), size = 0.05, stroke = 0), dpi = 600) +
    scale_color_de_gradient(abs_max, mid_width = 0.2) +
    scale_x_continuous(limits = range(umap_fit[,1]) * 1.1) +
    scale_y_continuous(limits = range(umap_fit[,2]) * 1.1) +
    small_axis(label = "", fontsize = font_size_tiny, xlim = range(umap_fit[,1]), ylim = range(umap_fit[,2]), arrow_length = 3) +
    theme(legend.position = "bottom")
de_plot_full

de_plot_split <- ggplot(de_plot_data_hist3h2a, aes(x = umap[,1], y = umap[,2])) +
    ggrastr::rasterise(geom_point(aes(color = de), size = 0.05, stroke = 0), dpi = 600) +
    scale_color_de_gradient(abs_max, mid_width = 0.2) +
    facet_wrap(vars(inside), ncol = 1, labeller = as_labeller(c("in" = "Cells in Neighborhood", "out" = "All other cells")))  +
    scale_x_continuous(limits = range(umap_fit[,1]) * 1.1) +
    scale_y_continuous(limits = range(umap_fit[,2]) * 1.1) +
    small_axis(label = "", fontsize = font_size_tiny, xlim = range(umap_fit[,1]), ylim = range(umap_fit[,2]), arrow_length = 3) +
    theme(legend.position = "bottom")
de_plot_split
```






```{r, paged.print=FALSE}
expr_plot_data <- as_tibble(colData(fit_small), rownames = "cell_id") %>%
  mutate(umap = umap_fit) %>%
  mutate(expr = as_tibble(as.matrix(t(assay(fit_small, "logcounts"))))) %>%
  unnest(expr, names_sep = "-") %>%
  pivot_longer(starts_with("expr-"), names_sep = "-", values_to = "expr", names_to = c(NA, "gid")) %>%
  inner_join(as_tibble(full_row_data), by = "gid") %>%
  sample_frac(size = 1)  %>%
  filter(gid %in% nei_pan_small$name | gid %in% nei_pan_tumor_small$name)



expr_plots <- expr_plot_data %>%
  filter(condition != "etoposide") %>%
  mutate(gene = factor(gene, levels = c(pan_genes_order[1], "LMO2", pan_genes_order[-1]))) %>%
  filter(! is.na(gene)) %>%
  group_by(gene) %>%
  group_map(\(data, key){
    data$gene <- key[[1]][1]

    ggplot(data, aes(x = umap[,1], y = umap[,2])) +
      ggrastr::rasterise(geom_point(aes(color = expr), size = 0.05, stroke = 0), dpi = 300) +
      geom_density2d(data = filter(rbind(de_regions_maps %>% mutate(gene = as.character(gene)), de_regions_maps2), gene == key[[1]]), breaks = 0.2, linewidth = 0.5,
                     contour_var = "ndensity", color = "black",
                     h = apply(umap_fit, 2, MASS::bandwidth.nrd) * 0.9,
                     show.legend = FALSE) +
      colorspace::scale_color_continuous_sequential(limits = c(0, quantile(data$expr, c(0.98))), oob = scales::oob_squish, palette = "Purples 2", n.breaks = 3) +
      facet_grid(vars(condition), vars(gene), labeller = labeller(gene = as_labeller(\(x) paste0("\\emph{", x, "}"))), switch = "y")  +
      scale_x_continuous(limits = range(umap_fit[,1]) * 1.1) +
      scale_y_continuous(limits = range(umap_fit[,2]) * 1.1) +
      small_axis(label = "", fontsize = font_size_tiny, xlim = range(umap_fit[,1]), ylim = range(umap_fit[,2]), arrow_length = 3) +
      guides(color = guide_colorbar(barheight = unit(1, "mm"), title = "")) +
      theme(panel.spacing.x = unit(5, "mm"), legend.position =  "bottom") +
      labs(color = "")
  }) %>%
  cowplot::plot_grid(plotlist = ., nrow = 1)



expr_plots
```



```{r, paged.print=FALSE}
pan_genes_ids <- deframe(full_row_data[, c("gene", "gid")])[c(pan_genes_order, "LMO2")]

mask <- matrix(NA, nrow = length(pan_genes_ids), ncol = ncol(fit_small), 
               dimnames = list(pan_genes_ids, colnames(fit_small)))
mask2 <- matrix(1, nrow = length(pan_genes_ids), ncol = ncol(fit_small), 
               dimnames = list(pan_genes_ids, colnames(fit_small)))
for(id in pan_genes_ids){
  if(id == "ENSG00000135363"){
    inside_cells <- intersect(colnames(fit_small), filter(nei_pan_tumor_small, name == id)$neighborhood[[1]])
  }else{
    inside_cells <- intersect(colnames(fit_small), filter(nei_pan_small, name == id)$neighborhood[[1]])
  }
  mask[id, inside_cells] <- 1
  mask2[id, inside_cells] <- NA
}

psce <- glmGamPoi::pseudobulk(SingleCellExperiment(list(inside = as.matrix(logcounts(fit_small)[pan_genes_ids,] * mask),
                                                        outside = as.matrix(logcounts(fit_small)[pan_genes_ids,] * mask2))),
                      group_by = vars(patient_id, condition, pat_cond), n = n(),
                      aggregation_functions = list(.default = \(...) matrixStats::rowMeans2(..., na.rm = TRUE)),
                      col_data = as.data.frame(colData(fit_small)))

comparison_plots <- as_tibble(colData(psce)) %>%
  mutate(expr_in = as_tibble(t(assay(psce, "inside")))) %>%
  mutate(expr_out = as_tibble(t(assay(psce, "outside")))) %>%
  unpack(starts_with("expr"), names_sep = "-") %>%
  pivot_longer(starts_with("expr"), names_sep = "[-_]", names_to = c(".value", "inside", "gid")) %>%
  left_join(as_tibble(full_row_data)) %>%
  filter(condition != "etoposide") %>%
  mutate(condition_short = case_when(
    condition == "ctrl" ~ "ctrl",
    condition == "panobinostat" ~ "pano.",
  )) %>%
  mutate(inside = factor(inside, levels = c("in", "out")))  %>%
  mutate(gene = factor(gene, levels = c(pan_genes_order[1], "LMO2", pan_genes_order[-1]))) %>%
  group_by(gene) %>%
  group_map(\(data, key){
    data$gene <- key[[1]][1]
    ggplot(data, aes(x = condition_short, y = expr)) +
      geom_point(aes(group = condition, color = condition), position = position_dodge(width = 0.7), size = 0.6, show.legend = FALSE) +
      geom_line(aes(group = patient_id, x = condition_short, y = expr), color = "lightgrey", linewidth = 0.3) +
      scale_color_manual(values = condition_colors) +
      scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.1)), n.breaks = 3) +
      coord_cartesian(clip = "off") +
      ggh4x::facet_nested(~ gene + inside, labeller = labeller(inside =as_labeller( c("in" = "Inside", "out" = "Outside")),
                                                               gene = as_labeller(\(x) paste0("\\emph{", x, "}"))),
                          strip = ggh4x::strip_nested(clip = "off"))  +
      guides(x = guide_axis(angle = 90)) +
      theme(axis.title.x = element_blank(), axis.text = element_text(size = font_size_tiny),
            strip.placement = "outside", panel.spacing.x = unit(2, "mm"))
  }) %>%
  cowplot::plot_grid(plotlist = ., nrow = 1)


comparison_plots
```


```{r}
comparison_pl <- as_tibble(colData(psce)) %>%
  mutate(expr_inside = as_tibble(t(assay(psce, "inside")))) %>%
  unpack(starts_with("expr"), names_sep = "-") %>%
  pivot_longer(starts_with("expr"), names_sep = "[-_]", names_to = c(".value", "origin", "gid")) %>%
  left_join(as_tibble(full_row_data)) %>%
  filter(condition != "etoposide") %>%
  mutate(condition_short = case_when(
    condition == "ctrl" ~ "ctrl",
    condition == "panobinostat" ~ "panob.",
  )) %>%
  mutate(gene = factor(gene, levels = pan_genes_order)) %>%
  filter(gene == "HIST3H2A") %>%
  ggplot(aes(x = condition_short, y = expr)) +
    geom_point(aes(group = condition, color = condition), position = position_dodge(width = 0.7), size = 0.6, show.legend = FALSE) +
    geom_line(aes(group = patient_id, x = condition_short, y = expr), color = "lightgrey", linewidth = 0.3) +
    scale_color_manual(values = condition_colors) +
    scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.2)), n.breaks = 3) +
    coord_cartesian(clip = "off") +
    # guides(x = guide_axis(angle = 90)) +
    labs(subtitle = "Pseudobulked expr. of\ncells in neighborhood") +
    theme(axis.title = element_blank(), plot.subtitle = element_text(size = font_size_small))

comparison_pl
```




```{r, paged.print=FALSE}
plot_assemble(add_text("(A) Expression pattern of selected genes under panobinostat treatment", x = 1.5, y = 1.5, vjust = 1, fontsize = font_size, fontface = "bold"),
              add_plot(expr_plots, x = 0, y = 5, width = 170, height = 50),
              add_text("(B) Predicted differential expression pattern ($\\Delta$)", x = 1.5, y = 57, vjust = 1, fontsize = font_size, fontface = "bold"),
              add_plot(de_plots, x = 0, y = 60, width = 170, height = 50),
              add_text("(C) Pseudobulked differential expression", x = 1.5, y = 117, vjust = 1, fontsize = font_size, fontface = "bold"),
              add_plot(comparison_plots, x = 0, y = 120, width = 170, height = 30),
              width = 170, height = 155, units = "mm", show_grid_lines = FALSE, latex_support = TRUE,
              filename = "../plots/suppl_gene_expr_patterns.pdf")
```


```{r, paged.print=FALSE}

is_inside2 <- tibble(gid = rowData(fit_small)$gid, gene = rowData(fit_small)$gene, cell_id = list(colnames(fit_small))) %>%
  filter(gid %in% "ENSG00000135363") %>%
  left_join(dplyr::select(nei_pan_tumor_small, name, neighborhood), by = c("gid"= "name")) %>%
  mutate(inside = map2(cell_id, neighborhood, \(ref, nei_cells)ref  %in% nei_cells)) %>%
  dplyr::select(-neighborhood) %>%
  unnest(c(inside, cell_id))

de_plot_data2 <- as_tibble(colData(fit_small), rownames = "cell_id") %>%
  mutate(umap = umap_fit) %>%
  mutate(de = as_tibble(t(assay(fit_small, "DE_panobinostat")))) %>%
  unnest(de, names_sep = "-") %>%
  pivot_longer(starts_with("de-"), names_sep = "-", values_to = "de", names_to = c(NA, "gid")) %>%
  inner_join(as_tibble(full_row_data), by = "gid") %>%
  inner_join(is_inside2, by = c("gid", "cell_id", "gene")) %>%
  filter(gid == "ENSG00000135363") %>%
  sample_frac(size = 1) 


abs_max <- max(abs(quantile(de_plot_data2$de, c(0.95, 0.05))))

  
de_plots2 <- de_plot_data2 %>%
  mutate(inside = ifelse(inside, "in", "out")) %>%
  mutate(inside = factor(inside, levels = c("in", "out")))  %>%
  mutate(de = ifelse(cell_type == "Tumor cells", de, NA)) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    ggrastr::rasterise(geom_point(aes(color = de), size = 0.05, stroke = 0), dpi = 600) +
    # scale_colour_gradient2_rev(limits = c(-1, 1) * abs_max, oob = scales::squish, breaks = c(-1, 0, 1) * signif_to_zero(abs_max, 1), mid = "lightgrey", na.value = "#00000000") +
    scale_color_de_gradient(abs_max, mid_width = 0.2, na.value = "#00000000") +
    facet_wrap(vars(inside), nrow = 1, labeller = as_labeller(c("in" = "Cells in Neighborhood", "out" = "Other tumor cells")))  +
    scale_x_continuous(limits = range(umap_fit[,1]) * 1.1) +
    scale_y_continuous(limits = range(umap_fit[,2]) * 1.1) +
    small_axis(label = "", fontsize = font_size_tiny, xlim = range(umap_fit[,1]), ylim = range(umap_fit[,2]), arrow_length = 3) +
    theme(panel.spacing.x = unit(-2, "mm"), legend.position = "bottom")

de_plots2
```



```{r, paged.print = FALSE}
genes_of_interest <- c("ENSG00000135363")

mask <- matrix(NA, nrow = length(genes_of_interest), ncol = ncol(fit_small), 
               dimnames = list(genes_of_interest, colnames(fit_small)))
mask2 <- matrix(1, nrow = length(genes_of_interest), ncol = ncol(fit_small), 
               dimnames = list(genes_of_interest, colnames(fit_small)))
for(id in genes_of_interest){
  inside_cells <- intersect(colnames(fit_small), filter(nei_pan_tumor_small, name == id)$neighborhood[[1]])
  mask[id, inside_cells] <- 1
  mask2[id, inside_cells] <- NA
}

psce2 <- glmGamPoi::pseudobulk(SingleCellExperiment(list(inside = as.matrix(logcounts(fit_small)[genes_of_interest,] * mask),
                                                        outside = as.matrix(logcounts(fit_small)[genes_of_interest,] * mask2))),
                      group_by = vars(patient_id, condition, pat_cond), n = n(),
                      aggregation_functions = list(.default = \(...) matrixStats::rowMeans2(..., na.rm = TRUE)),
                      col_data = as.data.frame(colData(fit_small)))

comparison_data2 <- as_tibble(colData(psce2)) %>%
  mutate(expr_inside = as_tibble(t(assay(psce2, "inside"))),
         expr_outside = as_tibble(t(assay(psce2, "outside")))) %>%
  unpack(starts_with("expr"), names_sep = "-") %>%
  pivot_longer(starts_with("expr"), names_sep = "[-_]", names_to = c(".value", "origin", "gid")) %>%
  left_join(as_tibble(full_row_data)) %>%
  filter(condition != "etoposide") %>%
  mutate(condition_short = case_when(
    condition == "ctrl" ~ "ctrl",
    condition == "panobinostat" ~ "panob.",
  ))

diff_df <-  comparison_data2 %>% 
  summarize(expr = mean(expr), .by = c(condition, origin)) %>% 
  pivot_wider(names_from = condition, values_from = expr)

comparison_pl2 <-  comparison_data2 %>%
  filter(patient_id != "PW029") %>%
  ggplot(aes(x = condition_short, y = expr)) +
    # geom_boxplot(outlier.shape =  NA, width = 0.3) +
    geom_line(aes(group = patient_id, x = condition_short, y = expr), color = "lightgrey", linewidth = 0.3) +
    geom_point(aes(group = condition, color = condition), position = position_dodge(width = 0.7), size = 0.8, show.legend = FALSE) +
    geom_segment(data = diff_df, aes(x = 1.5, y = ctrl, xend = 1.5, yend = panobinostat), color = "red", linewidth = 0.8, arrow = arrow(type = "closed", length = unit(1, "mm"))) +
    facet_grid(cols = vars(origin), labeller = as_labeller(c("inside" = "Cells in\nNeighborhood", "outside" = "Other tumor\ncells"))) +
    scale_color_manual(values = condition_colors) +
    scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.05)), n.breaks = 3) +
    coord_cartesian(clip = "off") +
    # guides(x = guide_axis(angle = 90)) +
    theme(panel.spacing.x = unit(1, "mm"), axis.title.x = element_blank()) +
    labs(y = "pseudobulked expr.")

diff_pl <- diff_df %>% 
  ggplot(aes(x = origin, xend = origin, y = 0, yend = panobinostat - ctrl)) +
    geom_hline(yintercept = 0) +
    geom_segment(color = "red", linewidth = 0.8, arrow = arrow(type = "closed", length = unit(1, "mm"))) +
    ggsignif::geom_signif(comparison = list(c("inside", "outside")), annotations = "**", textsize = font_size_small / .pt, y_position = 0.01) +
    scale_y_continuous(limits = c(-0.1, 0.1), expand = expansion(mult = c(0.05, 0.05)), n.breaks = 3) +
    labs(subtitle = "$ \\text{Diff. in diff.}$\n($\\Delta_{\\text{in}} - \\Delta_{\\text{out}}$)",
         y = "$\\Delta$") +
    theme(axis.title.x = element_blank(), plot.subtitle = element_text(hjust = 0.5)) 

comparison_pl2
diff_pl
```



```{r, paged.print=FALSE}
psce_lmo2_ctrl <- psce_lmo2[,psce_lmo2$condition == "ctrl"]
# glm_fit2 <- lemur:::edger_fit(counts(psce_lmo2_ctrl), design = ~ patient_id + inside, col_data = colData(psce_lmo2_ctrl),
#                              offset = log(glmGamPoi:::estimate_size_factors(counts(psce_lmo2_ctrl), method = "ratio")))
# glm_de_res <- lemur:::edger_test_de(glm_fit2, contrast = c(0, 0, 0, 0, 0, 0, 1))
glm_fit <- glmGamPoi::glm_gp(psce_lmo2[,psce_lmo2$condition == "ctrl"], design = ~ patient_id + inside, size_factors = "ratio", verbose = TRUE)
glm_de_res <- glmGamPoi::test_de(glm_fit, cond(inside = TRUE) - cond(inside = FALSE))

as_tibble(glm_de_res) %>%
  arrange(pval) %>%
  left_join(as_tibble(full_row_data), by = c("name" = "gid")) %>%
  print(n = 20)

```



```{r, paged.print=FALSE}
ego1 <- clusterProfiler::enrichGO(gene = glm_de_res %>% 
                                    # filter(lfc > +0.1) %>% 
                                    slice_min(pval, n = 200) %>% 
                                    pull(name), 
                                 universe = glm_de_res$name,
                                 OrgDb = org.Hs.eg.db::org.Hs.eg.db,
                                 keyType = "ENSEMBL",
                                 readable = TRUE,
                                 ont = "ALL")

# ego2 <- clusterProfiler::enrichGO(gene = glm_de_res %>% 
#                                     filter(lfc < -0.1) %>% 
#                                     slice_min(pval, n = 200) %>% 
#                                     pull(name), 
#                                  universe = glm_de_res$name,
#                                  OrgDb = org.Hs.eg.db::org.Hs.eg.db,
#                                  keyType = "ENSEMBL",
#                                  readable = TRUE,
#                                  ont = "ALL")
ekegg1 <- clusterProfiler::enrichKEGG(gene = glm_de_res %>% 
                                        slice_min(pval, n = 200) %>% 
                                        pull(name) %>% 
                                        clusterProfiler::bitr(fromType = "ENSEMBL", toType = "ENTREZID", OrgDb = org.Hs.eg.db::org.Hs.eg.db, drop=TRUE) %>% 
                                        pull(ENTREZID), 
                                 universe = clusterProfiler::bitr(glm_de_res$name, fromType = "ENSEMBL", toType = "ENTREZID", OrgDb = org.Hs.eg.db::org.Hs.eg.db, drop=TRUE)$ENTREZID,
                                 organism = "hsa",
                                 keyType = "kegg")


as_tibble(ego1) %>% print(n = 10)
# as_tibble(ego2) %>% print(n = 10)
as_tibble(ekegg1) %>% print(n = 10)

as_tibble(ego1) %>%
  filter(ID  == "GO:0002181")

# as_tibble(ego2) %>%
#   filter(ID  == "GO:0002181")
```


```{r}
neg_log10_trans <- scales::trans_new("neg_log10", trans = \(x) -log10(x),  inv = \(x) 10^(-x), domain = c(1e-100, Inf))


volcano_enrichment_pl <- as_tibble(glm_de_res) %>%
  # mutate(up_genes = name %in% ego1@geneSets[["GO:0006325"]]) %>%
  mutate(down_genes = name %in% ego1@geneSets[["GO:0002181"]]) %>%
  mutate(category = case_when(
    # up_genes ~ "Chromatin Reorganization",
    down_genes ~ "Cytopl. Transl. (GO:0002181)",
    TRUE ~ "other"
  )) %>%
  arrange(desc(category)) %>%
  mutate(lfc = ifelse(lfc < -2.7, -Inf, lfc)) %>%
  ggplot(aes(x = lfc, y = pval)) +
    ggrastr::rasterize(geom_point(data = . %>% filter(category == "other"), color = "lightgrey", stroke = 0, size = 0.2), dpi = 300) +
    ggrastr::rasterize(geom_point(data = . %>% filter(category != "other"), aes(color = category), stroke = 0, size = 0.6), dpi = 300) +
    small_arrow(label = "up inside", position = c(0.7, 0.98), offset = unit(0.95, "npc"), label_offset = unit(-1.3, "mm"), fontsize = font_size_tiny) +
    small_arrow(label = "down inside",position = c(0.3, 0.02),  offset = unit(0.95, "npc"), label_offset = unit(-1.3, "mm"), fontsize = font_size_tiny) +
    geom_hline(yintercept = max(glm_de_res$pval[glm_de_res$adj_pval < 0.1])) +
    scale_color_manual(values = c("Cytopl. Transl. (GO:0002181)" = "#8E063B")) +
    scale_y_continuous(limits = c(1, NA), expand = expansion(mult = c(0, 0.05)), trans = neg_log10_trans,
                       breaks = 10^seq(0, -11, by = -2), labels = \(x) glue("$10^{{{log10(x)}}}$")) +
    scale_x_continuous(limits = c(-3, 3)) +
    guides(color = guide_legend(override.aes = list(size = 2))) +
    labs(x = "Log fold change", y = "p-value", color = "") +
    theme(legend.position = "bottom")


volcano_enrichment_pl
```





```{r, paged.print=FALSE}
dim(fit_small)
table(nei_pan_mod$adj_pval < 0.1)
as_tibble(nei_pan_tumor_small) %>%
  left_join(as_tibble(rowData(fit_small)) %>% dplyr::select(name = gid, gene_name = gene)) 
table(fit_small$colData$cell_type)
sum(filter(is_inside2, gene == "LMO2")$inside)
sum(fit_small$colData$cell_type == "Tumor cells") - sum(filter(is_inside2, gene == "LMO2")$inside)
```



```{r}
cell_type_legend <- my_get_legend(
  ggplot(enframe(cell_type_colors), aes(x = 0, y = 0, color = name)) + 
    geom_point() + 
    scale_color_manual(values = cell_type_colors, name = "Cell types") +
    theme(legend.position = "left", legend.title = element_text(size = font_size)))

condition_legend <- my_get_legend(
  ggplot(enframe(condition_colors) %>% filter(name != "etoposide"), aes(x = 0, y = 0, color = name)) + 
    geom_point() + 
    scale_color_manual(values = condition_colors, name = "Conditions") +
    theme(legend.position = "left", legend.title = element_text(size = font_size)))
  
# hist3h2a_legend <- cowplot::get_legend({
#   de_plot_full +
#     guides(color = guide_colorbar(title = "", label.theme = element_text(size = font_size_tiny, margin = margin(t = 0 , unit = "mm")), 
#                                  barheight = unit(1.5, "mm"), barwidth = unit(23, "mm")))
# })

lmo2_legend <- my_get_legend({
  de_plots2 +
    guides(color = guide_colorbar(title = "", label.theme = element_text(size = font_size_tiny, margin = margin(t = 0.5, unit = "mm")), 
                                 barheight = unit(1.5, "mm"), barwidth = unit(21, "mm")))
})

volcano_legend <- my_get_legend({
  volcano_enrichment_pl + 
    guides(color = guide_legend(override.aes = list(size = 1))) + 
    labs(color = "")
})

```



```{r}
row1_umap_width <- 48

plot_assemble(
  add_text("(A) Glioblastoma experimental design", x = 1.5, y = 1.5, vjust = 1, fontsize = font_size, fontface = "bold"),
  add_graphic("../illustrations/glioblastoma_experiment_overview_wideArtboard 1.pdf", x = 1.5,  y = 2.5, units = "mm"),
  
  add_text("(B) Integration with LEMUR adjusting for patient and treatment effect", x = 1.5, y = 24.5, vjust = 1, fontsize = font_size, fontface = "bold"),
  add_plot(condition_legend, x = 3, y = 31 , height = 34),
  add_text("UMAP of $\\matr{Y}$", x = 25 + row1_umap_width * 0.5, y = 30, vjust = 1, hjust = 0.5, fontsize = 7),
  add_text("UMAP of $\\matr{Z}$ if $\\matr{S} = I$", x = 25 + row1_umap_width * 1.5, y = 30, vjust = 1, hjust = 0.5, fontsize = 7),
  add_text("UMAP of $\\matr{Z}$ if $\\matr{S}$ estimated with Harmony", x = 25 + row1_umap_width * 2.5, y = 30, vjust = 1, hjust = 0.5, fontsize = 7),
  add_plot(umap_orig_pc_pl, x = 25 + row1_umap_width * 0, y = 31, width = row1_umap_width, height = 40),
  add_plot(umap_fit_pc_pl, x = 25 + row1_umap_width * 1, y = 31, width = row1_umap_width, height = 40),
  add_plot(umap_fital_pc_pl, x = 25 + row1_umap_width * 2, y = 31, width = row1_umap_width, height = 40),

  add_plot(cell_type_legend, x = 3, y = 70, height = 40),
  add_plot(umap_orig_ct_pl, x = 25 + row1_umap_width * 0, y = 70, width = row1_umap_width, height = 40),
  add_plot(umap_fit_ct_pl, x = 25 + row1_umap_width * 1, y = 70, width = row1_umap_width, height = 40),
  add_plot(umap_fital_ct_pl, x = 25 + row1_umap_width * 2, y = 70, width = row1_umap_width, height = 40),

  add_text("(C) Panobinostat down-regulates \\emph{LMO2} in a subpopulation of tumor cells", x = 1.5, y = 111, vjust = 1, fontsize = font_size, fontface = "bold"),
  add_plot(de_plots2 + guides(color = "none"), x = 0, y = 113, width = 61, height = 40),
  add_plot(lmo2_legend, x = 16.5, y = 151, width = 30, height = 5),
  add_text("down", x = 16, y = 150.9, vjust = 1, fontsize = font_size_small, hjust = 1),
  add_text("regulation", x = 16, y = 152.9, vjust = 1, fontsize = font_size_small, hjust = 1),
  add_text("up", x = 40.5, y = 150.9, vjust = 1, fontsize = font_size_small, hjust = 0),
  add_text("regulation", x = 40.5, y = 152.9, vjust = 1, fontsize = font_size_small, hjust = 0),
  add_plot(comparison_pl2, x = 61, y = 114, width = 45, height = 41.8),
  add_plot(diff_pl, x = 104, y = 115, width = 25, height = 40.5),


  add_text("(D) Characterization of tumor\n\\quad\\quad subpopulation", x = 130, y = 111, vjust = 1, fontsize = font_size, fontface = "bold"),
  add_plot(volcano_legend, x = 133, y = 117, width = 36, height = 4),
  add_plot(volcano_enrichment_pl + guides(color = "none"), x = 129, y = 119, width = 41, height = 39),
  
  width = 170, height = 159, units = "mm", show_grid_lines = FALSE, latex_support = TRUE,
  filename = "../plots/glioblastoma_results.pdf")
```



```{r, paged.print=FALSE}
tab <- colData(fit_small) %>%
  as_tibble() %>%
  mutate(treatment = factor(treatment, levels = c("vehicle (DMSO)", "0.2 uM panobinostat", "2.5 uM etoposide"))) %>%
    group_by(patient_id, treatment, pat_cond, age, gender, location) %>%
  summarize(n_cells = n(), .groups = "drop") %>%
  dplyr::select(`Patient ID` = patient_id, Age = age, Gender = gender,
                `Tumor location` = location, Conditon = treatment, `\\# Cells` = n_cells) %>%
  mutate(across(everything(), as.character)) %>%
  mutate(across(everything(), \(x) ifelse(x == lag(x, default = ""), "", x)), .by = `Patient ID`) %>%
  mutate(`Patient ID` = ifelse(`Patient ID` == lag(`Patient ID`, default = ""), "", `Patient ID`)) %>%
  kableExtra::kbl(booktabs = TRUE, format = "latex", escape = FALSE, linesep = "") %>%
  kableExtra::kable_styling(latex_options = "striped", stripe_index = c(1:2, 5:6, 9:10))

str_split(tab, "\n")[[1]] %>%
  magrittr::extract(., 2:(length(.)-1)) %>%
  write_lines("../plots/patient_overview_table.tex")
```





```{r}
sessionInfo()
```



