---
title: "R Notebook"
---

```{r}
library(tidyverse)
library(glue)
library(SingleCellExperiment)
library(lemur)
source("util.R")
```

```{r}
neural_genes <- c("iqsec1b", "nrxn2a")
neural_gene_ids <- c("ENSDARG00000016551", "ENSDARG00000061454")
periderm_genes <- c("krt18a.1", "krt8","slc6a9")
periderm_gene_ids <- c("ENSDARG00000058358", "ENSDARG00000018404", "ENSDARG00000018534")
```




```{r}
fit_subset <- qs::qread("../benchmark/output/zebrafish/saunders_zebrafish-fit_5_genes.qs")
umaps <- qs::qread("../benchmark/output/zebrafish/saunders_zebrafish-umap_embeddings.qs")
```


Time course

```{r}
timepoint_brackets <- santoku::chop_evenly(fit_subset$colData$timepoint, intervals = 5)

time_course_pl <- as_tibble(colData(fit_subset)) %>%
  mutate(timepoint_brackets = timepoint_brackets) %>%
  mutate(umap = umaps$umap_all) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    ggrastr::rasterize(geom_point(data = tibble(umap = umaps$umap_all), size = 0.1, stroke = 0, color = "grey85"), dpi = 300) +
    ggrastr::rasterize(geom_point(size = 0.01, stroke = 0, color = "black", alpha = 0.3), dpi = 600) +
    facet_wrap(vars(timepoint_brackets), nrow = 1, labeller = as_labeller(\(x) paste0("Timepoints: ", x))) +
    small_axis(label = "UMAP")
  
time_course_pl
```

```{r, paged.print=FALSE}
set.seed(1)
celltype_broad_plt <- as_tibble(colData(fit_subset)) %>%
  mutate(umap = umaps$umap_all) %>%
  mutate(tissue_mod = case_when(
    tissue == "Epidermis" ~ cell_type_broad,
    TRUE ~ tissue
  )) %>%
  mutate(cell_type_label = tissue_mod) %>%
  mutate(cell_type_label = fct_lump_n(cell_type_label, n = 10)) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    ggrastr::rasterize(geom_point(aes(color = cell_type_label), size = 0.01, stroke = 0, show.legend = FALSE), dpi = 600) +
    ggrepel::geom_text_repel(data = . %>% summarize(umap = matrix(colMedians(umap), nrow = 1), .by = cell_type_label), 
                              aes(label = cell_type_label), size = font_size_tiny / .pt, show.legend = FALSE, max.overlaps = 100) +
    scale_x_continuous(limits = range(umaps$umap_all[,2])) +
    small_axis(label = "UMAP", fontsize = font_size_small,
                xlim = scales::expand_range(quantile(umaps$umap_all[,1], c(0.01, 0.99)), mul = 0)) +
    labs(title = "(A) Zebrafish: tissue labels plus zoom in on cell types in central nervous system and periderm") 

celltype_specific_plt <- as_tibble(colData(fit_subset)) %>%
  mutate(umap = umaps$umap_all) %>%
  mutate(split_label = case_when(
    cell_type_broad == "periderm" ~ "Periderm",
    tissue == "Central Nervous System" ~ "Central Nervous System",
    TRUE ~ "Other"
  )) %>%
  filter(split_label != "Other") %>%
  mutate(cell_type_label = cell_type_sub) %>%
  group_by(split_label) %>%
  group_map(\(data, key){
    y_mult <- if(key[[1]][1] == "Central Nervous System") 0.2 else 0.5
    x_mult <- if(key[[1]][1] == "Central Nervous System") 0.2 else 0.5
    data %>%
      mutate(split_label = key[[1]][1]) %>%
      mutate(cell_type_label = fct_lump_n(cell_type_label, n = 6)) %>%
      ggplot(aes(x = umap[,1], y = umap[,2])) +
        ggrastr::rasterize(geom_point(aes(color = cell_type_label), size = 0.01, stroke = 0, show.legend = FALSE), dpi = 600) +
        ggrepel::geom_text_repel(data = . %>% summarize(umap = matrix(colMedians(umap), nrow = 1), .by = c(split_label, cell_type_label)), 
                                  aes(label = stringr::str_wrap(cell_type_label, 20)), size = font_size_tiny / .pt, 
                                 max.overlaps = 20, box.padding = 0.5, show.legend = FALSE) +
        facet_wrap(vars(split_label)) +
        small_axis(label = "UMAP", fontsize = font_size_small, 
                   xlim = scales::expand_range(quantile(data$umap[,1], c(0.05, 0.95)), mul = x_mult),
                   ylim = scales::expand_range(quantile(data$umap[,2], c(0.05, 0.95)), mul = y_mult))
  }) %>%
  cowplot::plot_grid(plotlist = ., nrow = 1, rel_widths = c(1, 0.5))

comb_cell_type_pl <- cowplot::plot_grid(celltype_broad_plt, celltype_specific_plt, nrow = 1, rel_widths = c(1.1, 2))
cowplot::save_plot("../plots/suppl_zebrafish_cell_types.pdf", comb_cell_type_pl, base_height = 8, base_width = 17, units = "cm", ncol = 1)
```




```{r}
emb <- fit_subset$embedding
  
start_cell1 <- "F08_B03_P04-C07_LIG124"
end_cell1 <- "G11_G02_P04-G08_LIG122"
interpolation1 <- t(lemur:::mply_dbl(seq(0, 1, l = 100), \(f){
  emb[,start_cell1] + f * (emb[,end_cell1] - emb[,start_cell1])
}, ncol = nrow(emb)))

start_cell2 <- "H04_H03_P03-C11_LIG190"
end_cell2 <- "G04_H11_P03-E03_LIG290"
interpolation2 <- t(lemur:::mply_dbl(seq(0, 1, l = 100), \(f){
  emb[,start_cell2] + f * (emb[,end_cell2] - emb[,start_cell2])
}, ncol = nrow(emb)))
```


```{r}
n_pos <- 10
sel_pos <- seq(1, nrow(umaps$umap_inter1), l = n_pos)

umap_pl <- as_tibble(colData(fit_subset)) %>%
  mutate(umap = umaps$umap_all) %>%
  ggplot(aes(x = umap[,1], y = umap[,2])) +
    annotate(geom = "text", x = -5, y = 5, label = "Central nervous system", size = font_size_small / .pt) +
    annotate(geom = "text", x = 8, y = 6, label = "Periderm", size = font_size_small / .pt) +
    ggrastr::rasterize(geom_point(size = 0.2, stroke = 0, color = "grey85"), dpi = 600) +
    geom_point(data = tibble(umap = umaps$umap_inter1[sel_pos,], position = seq(0, 1, l = n_pos)), aes(fill = position), shape = 21, color = "black", size = 1.3, stroke = 0.1) +
    colorspace::scale_fill_continuous_divergingx(palette = "Zissou1", mid = 0.5) +
    ggnewscale::new_scale_fill() +
    geom_point(data = tibble(umap = umaps$umap_inter2[sel_pos,], position = seq(0, 1, l = n_pos)), aes(fill = position), shape = 21, color = "black", size = 1.3, stroke = 0.1) +
    colorspace::scale_fill_continuous_divergingx(palette = "Tropic", mid = 0.5) +
    small_axis(label = "UMAP") 

umap_pl
```



```{r}
set.seed(1)
obs_gene_expr <- bind_rows(map(levels(timepoint_brackets), \(brack){
  fit_br <- fit_subset[,timepoint_brackets == brack]
  knn_index <- BiocNeighbors::buildAnnoy(t(fit_br$embedding))
  close_to_interpol <- BiocNeighbors::queryAnnoy(precomputed = knn_index, query = t(interpolation1), k = 50, get.index = TRUE, get.distance = FALSE)$index
  bind_rows(
    as_tibble(t(as.matrix(logcounts(fit_br)[neural_gene_ids, close_to_interpol[1,]]))) %>% mutate(origin = 0),
    as_tibble(t(as.matrix(logcounts(fit_br)[neural_gene_ids, close_to_interpol[round(ncol(interpolation1) * 0.25),]]))) %>% mutate(origin = 0.25),
    as_tibble(t(as.matrix(logcounts(fit_br)[neural_gene_ids, close_to_interpol[round(ncol(interpolation1) * 0.5),]]))) %>% mutate(origin = 0.5),
    as_tibble(t(as.matrix(logcounts(fit_br)[neural_gene_ids, close_to_interpol[round(ncol(interpolation1) * 0.75),]]))) %>% mutate(origin = 0.75),
    as_tibble(t(as.matrix(logcounts(fit_br)[neural_gene_ids, close_to_interpol[round(ncol(interpolation1)),]]))) %>% mutate(origin = 1),
  ) %>%
    mutate(timepoint_br = brack)
}))

pred_expr_df <- tibble(timepoint = c(seq(18, 48, length = 50))) %>%
  mutate(pred = map(timepoint, \(ti) as_tibble(predict(fit_subset, embedding = interpolation1[,sel_pos], newcondition = cond(timepoint = ti))))) %>%
  mutate(gene_id = list(rownames(fit_subset))) %>%
  unnest(c(gene_id, starts_with("pred")), names_sep = "-") %>%
  pivot_longer(starts_with("pred"), names_sep = "-", names_to = c(".value", "origin")) %>%
  mutate(origin = as.integer(str_remove(origin, "V"))) %>%
  mutate(origin = origin / max(origin)) %>%
  left_join(as_tibble(rowData(fit_subset)), by = c("gene_id" = "id")) %>%
  filter(gene_short_name %in% neural_genes)

obs_expr_df <- obs_gene_expr %>%
  pivot_longer(starts_with("ENSDAR"), names_to = "gene_id", values_to = "expr") %>%
  mutate(timepoint_br = factor(timepoint_br, levels = levels(timepoint_brackets))) %>%
  left_join(as_tibble(rowData(fit_subset)), by = c("gene_id" = "id")) %>% 
  mutate(timepoint = str_extract_all(timepoint_br, "\\d+\\.?\\d*") %>% map_dbl(\(x) mean(as.numeric(x))))

pred_plot <- pred_expr_df %>%
  ggplot(aes(x = timepoint, y = pred)) +
    geom_line(aes(color = origin, group = as.factor(origin))) +
    geom_point(data = obs_expr_df %>% summarize(timepoint = median(timepoint), expr = mean(expr), .by = c(gene_short_name, timepoint_br, origin)),
               aes(y = expr, fill = origin), shape = 21, color = "black", size = 2) +
    geom_text(data = tibble(label = "Average of cells near the blue\nposition for timepoints 18h-24h.", gene_short_name = "iqsec1b"),
              aes(label = label), x = 18, y = 2.5, hjust = 0, vjust = 0.5, size = font_size_tiny / .pt) +
    geom_segment(data = tibble(x = 24, y = 2.0, xend = 21, yend = 0.983, gene_short_name = "iqsec1b"),
                 aes(x = x, y = y, xend = xend, yend = yend)) +
    geom_text(data = tibble(label = "LEMUR's prediction for\nthe blue position at 35h", gene_short_name = "iqsec1b"),
              aes(label = label), x = 36.5, y = 2, hjust = 0, vjust = 0.5, size = font_size_tiny / .pt) +
    geom_segment(data = tibble(x = 36, y = 1.5, xend = 35, yend = 0.758, gene_short_name = "iqsec1b"),
                 aes(x = x, y = y, xend = xend, yend = yend)) +
    facet_wrap(vars(gene_short_name), scales = "free_y", labeller = as_labeller(\(x)glue("\\emph{{{x}}}"))) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1)), limits = c(0, 3)) +
    scale_x_continuous(breaks = c(18, 24, 30, 36, 42, 48)) +
    # coord_cartesian(clip = "off") +
    colorspace::scale_fill_continuous_divergingx(palette = "Zissou1", mid = 0.5) +
    colorspace::scale_color_continuous_divergingx(palette = "Zissou1", mid = 0.5) +
    guides(fill = "none") +
    labs(y = "Expression", x = "Hours post fertilization",
         subtitle = "Central Nervous System") +
    theme(plot.subtitle = element_text(size = font_size_small, margin = margin(t = 0, unit = "mm")))

pred_plot
```



```{r, paged.print=FALSE}
set.seed(1)
obs_gene_expr2 <- bind_rows(map(levels(timepoint_brackets), \(brack){
  fit_br <- fit_subset[,timepoint_brackets == brack]
  knn_index <- BiocNeighbors::buildAnnoy(t(fit_br$embedding))
  close_to_interpol <- BiocNeighbors::queryAnnoy(precomputed = knn_index, query = t(interpolation2), k = 50, get.index = TRUE, get.distance = FALSE)$index
  bind_rows(
    as_tibble(t(as.matrix(logcounts(fit_br)[periderm_gene_ids, close_to_interpol[1,]]))) %>% mutate(origin = 0),
    as_tibble(t(as.matrix(logcounts(fit_br)[periderm_gene_ids, close_to_interpol[round(ncol(interpolation2) * 0.25),]]))) %>% mutate(origin = 0.25),
    as_tibble(t(as.matrix(logcounts(fit_br)[periderm_gene_ids, close_to_interpol[round(ncol(interpolation2) * 0.5),]]))) %>% mutate(origin = 0.5),
    as_tibble(t(as.matrix(logcounts(fit_br)[periderm_gene_ids, close_to_interpol[round(ncol(interpolation2) * 0.75),]]))) %>% mutate(origin = 0.75),
    as_tibble(t(as.matrix(logcounts(fit_br)[periderm_gene_ids, close_to_interpol[round(ncol(interpolation2)),]]))) %>% mutate(origin = 1),
  ) %>%
    mutate(timepoint_br = brack)
}))

pred_expr_df2 <- tibble(timepoint = c(seq(18, 48, length = 50))) %>%
  mutate(pred = map(timepoint, \(ti) as_tibble(predict(fit_subset, embedding = interpolation2[,sel_pos], newcondition = cond(timepoint = ti))))) %>%
  mutate(gene_id = list(rownames(fit_subset))) %>%
  unnest(c(gene_id, starts_with("pred")), names_sep = "-") %>%
  pivot_longer(starts_with("pred"), names_sep = "-", names_to = c(".value", "origin")) %>%
  mutate(origin = as.integer(str_remove(origin, "V"))) %>%
  mutate(origin = origin / max(origin)) %>%
  left_join(as_tibble(rowData(fit_subset)), by = c("gene_id" = "id")) %>%
  filter(gene_short_name %in% periderm_genes)

obs_expr_df2 <- obs_gene_expr2 %>%
  pivot_longer(starts_with("ENSDAR"), names_to = "gene_id", values_to = "expr") %>%
  mutate(timepoint_br = factor(timepoint_br, levels = levels(timepoint_brackets))) %>%
  left_join(as_tibble(rowData(fit_subset)), by = c("gene_id" = "id")) %>% 
  mutate(timepoint = str_extract_all(timepoint_br, "\\d+\\.?\\d*") %>% map_dbl(\(x) mean(as.numeric(x)))) %>%
  filter(gene_short_name %in% periderm_genes[c(2,3)])

pred_plot2 <- pred_expr_df2 %>%
  filter(gene_short_name %in% periderm_genes[c(2,3)]) %>%
  filter(pred < 2.2) %>%
  ggplot(aes(x = timepoint, y = pred)) +
    geom_line(aes(color = origin, group = as.factor(origin))) +
    geom_point(data = obs_expr_df2 %>% summarize(timepoint = median(timepoint), expr = mean(expr), .by = c(gene_short_name, timepoint_br, origin)),
               aes(y = expr, fill = origin), shape = 21, color = "black", size = 2) +
    geom_blank(data = tibble(timepoint = 30, pred = 1)) +
    facet_wrap(vars(gene_short_name), scales = "free_y", labeller = as_labeller(\(x)glue("\\emph{{{x}}}"))) +
    scale_x_continuous(breaks = c(18, 24, 30, 36, 42, 48)) +
    # scale_y_continuous(expand = expansion(mult = c(0, 0)), limits = c(0, 2.2)) +
    scale_y_continuous(expand = expansion(mult = c(0, 0))) +
    colorspace::scale_fill_continuous_divergingx(palette = "Tropic", mid = 0.5) +
    colorspace::scale_color_continuous_divergingx(palette = "Tropic", mid = 0.5) +
    guides(fill = "none") +
    labs(y = "Expression", x = "Hours post fertilization",
         subtitle = "Periderm") +
    theme(plot.subtitle = element_text(size = font_size_small, margin = margin(t = 0, unit = "mm")))

pred_plot2
```





```{r, paged.print=FALSE}
kerat_expr_df <- as_tibble(colData(fit_subset)) %>%
  mutate(timepoint_brackets = timepoint_brackets) %>%
  mutate(umap = umaps$umap_all) %>%
  mutate(expr = logcounts(fit_subset)["ENSDARG00000058358",]) %>%
  filter(cell_type_broad == "periderm")
  

kerat_expr_pl <- ggplot(kerat_expr_df, aes(x = umap[,1], y = umap[,2])) +
    ggrastr::rasterize(geom_point(aes(color = expr), size = 0.1, stroke = 0, show.legend = TRUE), dpi = 600) +
    geom_point(data = tibble(umap = umaps$umap_inter2[sel_pos,], position = seq(0, 1, l = n_pos)), aes(fill = position), shape = 21, 
               color = "black", size = 1.8, stroke = 0.2, show.legend = FALSE) +
    colorspace::scale_fill_continuous_divergingx(palette = "Tropic", mid = 0.5) +
    scale_color_gradient(low = "lightgrey", high = "#3d2892", limits = c(0, quantile(logcounts(fit_subset)["ENSDARG00000058358",], c(0.95))), oob = scales::oob_squish) +
    facet_wrap(vars(timepoint_brackets), nrow = 1) +
    small_axis(label = "UMAP", fontsize = font_size_small, 
               xlim = scales::expand_range(quantile(kerat_expr_df$umap[,1], c(0.05, 0.95)), mul = 0.5),
               ylim = scales::expand_range(quantile(kerat_expr_df$umap[,2], c(0.05, 0.95)), mul = 0.5)) +
    labs(title = "Gene expression of \\emph{krt8} in the periderm over time")

plot_assemble(
  add_plot(kerat_expr_pl, x = 0, y = 1, width = 170, height = 50),
  width = 170, height = 50, units = "mm", show_grid_lines = FALSE,
  latex_support = TRUE, filename = "../plots/suppl_kerat_expr_plot.pdf"
)
```


```{r}
plot_assemble(
  add_text("(A) Zebrafish embryo development time course (hours post fertilization)", x = 2.7, y = 1, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(time_course_pl, x = 0, y = 3, width = 170, height = 50),
  add_text("(B) Synthetic cells projected on UMAP", x = 2.7, y = 53, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(umap_pl + theme(legend.position = "none"), x = 0, y = 56, width = 60, height = 57),
  add_text("(C) Predicted interactions between time and coordinates in latent space",
           x = 62.7, y = 53, fontsize = font_size, vjust = 1, fontface = "bold"),
  add_plot(pred_plot + theme(legend.position = "none"), x = 60, y = 56, width = 110, height = 30.5),
  add_plot(pred_plot2  + theme(legend.position = "none"), x = 60, y = 55+30.5, width = 110, height = 30.5),

  width = 170, height = 116, units = "mm", show_grid_lines = FALSE,
  latex_support = TRUE, filename = "../plots/continuous_covar_figure.pdf"
)

```



# Session Info

```{r}
sessionInfo()
```

